# # Use postgres/example user/password credentials
# services:
#   # postgres:
#   #   image: postgres:17
#   #   container_name: quizpilot_db
#   #   restart: always
#   #   environment:
#   #     POSTGRES_DB: ${DB_NAME}
#   #     POSTGRES_USER: ${DB_USER}
#   #     POSTGRES_PASSWORD: ${DB_PASSWORD}
#   #   ports:
#   #     - "${PG_PORT:-5435}:5432"
#   #   volumes:
#   #     - postgres_data:/var/lib/postgresql/data
#   #     # - ./src/scripts_sql:/docker-entrypoint-initdb.d/

#   api:
#     image: ${DOCKERHUB_USERNAME}/quizpilot_api:latest
#     container_name: quizpilot_api
#     restart: always
#     ports:
#       - 8000:8000
#     env_file:
#       - .env
#     # volumes:
#     #   - ./back-django:/usr/src/app
#     # depends_on:
#     #   - postgres

#   client:
#     image: ${DOCKERHUB_USERNAME}/quizpilot_client:latest
#     container_name: quizpilot_client
#     restart: always
#     ports:
#       - "3010:80"
#       # à supprimer si front derrière nginx ?
#     env_file:
#       - .env
#     # volumes:
#     #   - ./client:/usr/src/app
#     depends_on:
#       - api
# # volumes:
# #   postgres_data:

# # pas de n8n ?


services:
  postgres:
    image: postgres:15
    container_name: quizpilot_db_new # Un nom différent pour ne pas heurter l'actuel
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5436:5432" # Un port différent (5436) au lieu de l'actuel
    volumes:
      - postgres_data_new:/var/lib/postgresql/data
    networks:
      - app_network

  api:
    image: ${DOCKERHUB_USERNAME}/quizpilot_api:latest
    container_name: quizpilot_api_new
    restart: always
    ports:
      - 8001:8000 # Nouveau port
    env_file: .env
    depends_on:
      - postgres
    networks:
      - app_network

  client:
    image: ${DOCKERHUB_USERNAME}/quizpilot_client:latest
    container_name: quizpilot_client_new
    restart: always
    ports:
      - "3011:80" # Nouveau port
    env_file: .env
    depends_on:
      - api
    networks:
      - app_network

  n8n:
    image: n8nio/n8n:latest
    container_name: quizpilot_n8n_new
    restart: unless-stopped
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${N8N_DB}
      - DB_POSTGRESDB_USER=${DB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_PASSWORD}
      - N8N_HOST=${N8N_HOST}
      - N8N_PROTOCOL=https
      - NODE_ENV=production
    volumes:
      - n8n_data_new:/home/node/.n8n
    ports:
      - "5679:5678" # Nouveau port
    depends_on:
      - postgres
    networks:
      - app_network

volumes:
  postgres_data_new:
  n8n_data_new:

networks:
  app_network:
    driver: bridge