# Use postgres/example user/password credentials
services:
  postgres:
    image: postgres:15
    container_name: quizpilot_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${PG_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/scripts_sql:/docker-entrypoint-initdb.d/

  api:
    build:
      context: ./back-django
      dockerfile: Dockerfile
    container_name: quizpilot_api
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./back-django:/usr/src/app
    depends_on:
      - postgres

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_N8N_WEBHOOK_URL: ${VITE_N8N_WEBHOOK_URL:-http://localhost:5678/webhook}
    container_name: quizpilot_client
    restart: always
    ports:
      - "${FRONT_PORT:-3005}:80"
      # à supprimer si front derrière nginx ?
    env_file:
      - .env
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - api

  n8n:
    image: n8nio/n8n:latest
    container_name: quizpilot_n8n_local
    restart: unless-stopped
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: quizpilot_db
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${N8N_DB}
      DB_POSTGRESDB_USER: ${DB_USER}
      DB_POSTGRESDB_PASSWORD: ${DB_PASSWORD}
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: ${N8N_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_PASSWORD}
      N8N_HOST: ${N8N_HOST}
      N8N_PORT: 5678
      N8N_PROTOCOL: ${N8N_PROTOCOL}
      WEBHOOK_URL: ${WEBHOOK_URL}
      GENERIC_TIMEZONE: ${TZ}
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
    volumes:
      - n8n_local_data:/home/node/.n8n
    ports:
      - "5678:5678"
    depends_on:
      - postgres

volumes:
  postgres_data:
  n8n_local_data:
