# Use postgres/example user/password credentials
services:
  postgres:
    image: postgres:latest
    container_name: quizpilot_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${PG_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/scripts_sql:/docker-entrypoint-initdb.d/

  api:
    image: ${DOCKERHUB_USERNAME}/quizpilot_api:latest
    container_name: quizpilot_api
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./back-django:/usr/src/app
    depends_on:
      - postgres

  client:
    image: ${DOCKERHUB_USERNAME}/quizpilot_client:latest
    container_name: quizpilot_client
    restart: always
    ports:
      - "3010:3000"
    env_file:
      - .env
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - api

volumes:
  postgres_data:
