name: Build and Deploy to VPS

# quand une push est faite sur la branche main
on:
  push:
    branches:
      - "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # cloner le repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # se connecter à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # construire et pousser les images - API
      - name: Build and push API
        uses: docker/build-push-action@v6
        with:
          context: ./back-django
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/quizpilot_api:latest

      # construire et pousser les images - Client
      - name: Build and push Client
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/quizpilot_client:latest
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}
            VITE_N8N_WEBHOOK_URL=${{ secrets.VITE_N8N_WEBHOOK_URL }}

  deploy:
    # needs permet d'attendre la fin du job build-and-push avant de lancer le déploiement
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      # cloner le repo (à nouveau, car chaque job est isolé)
      - name: Checkout repository
        uses: actions/checkout@v4

      # créer le dossier sur le VPS distant en SSH
      - name: Create directory on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: mkdir -p /home/debian/quizpilot-docker

      # copier le fichier docker-compose.prod.yml sur le VPS distant (toujours en ssh)
      - name: Copy docker-compose.prod.yml to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          # à voir : ameliorer avec avec key: ${{ secrets.VPS_SSH_KEY }} au lieu de password ?
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "docker-compose.prod.yml"
          target: "/home/debian/quizpilot-docker"

      # se connecter en SSH sur le VPS et lancer le déploiement
      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          # créer le fichier .env avec les secrets, arrêter et supprimer les conteneurs existants, pull des nouvelles images, et relancer les conteneurs
          # voir pour ajouter set-e -e pour arrêter en cas d'erreur ?
          # voir pour ajouter helthcheck avant/après le sleep 20 ?
          #. Si aucun conteneur ne correspond au filtre, docker stop peut échouer et bloquer le script
          # donc voir pour ajouter :
          # docker stop $(docker ps -q --filter "name=^quizpilot") 2>/dev/null || true
          # docker rm -f $(docker ps -aq --filter "name=^quizpilot") 2>/dev/null || true
          script: |
            cd /home/debian/quizpilot-docker

            # Génération du fichier .env
            echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" > .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=\"${{ secrets.DB_PASSWORD }}\"" >> .env
            echo "DB_HOST=postgres" >> .env
            echo "DB_PORT=5432" >> .env
            
            # Variables pour n8n (à ajouter dans les secrets GitHub)
            echo "N8N_DB=${{ secrets.N8N_DB }}" >> .env
            echo "N8N_ENCRYPTION_KEY=${{ secrets.N8N_ENCRYPTION_KEY }}" >> .env
            echo "N8N_HOST=${{ secrets.N8N_HOST }}" >> .env
            echo "N8N_PROTOCOL=https" >> .env
            echo "N8N_PROXY_HOPS=1" >> .env
            echo "N8N_SECURE_COOKIE=false" >> .env
            echo "N8N_DEFAULT_BINARY_DATA_MODE=filesystem" >> .env
            echo "WEBHOOK_URL=https://${{ secrets.N8N_HOST }}/" >> .env
            
            echo "ALLOWED_HOSTS=\"${{ secrets.ALLOWED_HOSTS }}\"" >> .env
            echo "SECRET_KEY=\"${{ secrets.SECRET_KEY }}\"" >> .env
            echo "DEBUG=${{ secrets.DEBUG }}" >> .env
            echo "CORS_ALLOWED_ORIGINS=\"${{ secrets.CORS_ALLOWED_ORIGINS }}\"" >> .env
            echo "CSRF_TRUSTED_ORIGINS=\"${{ secrets.CORS_ALLOWED_ORIGINS }}\"" >> .env

            # Nettoyage agressif : on stoppe tous les types d'anciens containers pour libérer les ports
            docker stop quizpilot_api quizpilot_client quizpilot_db quizpilot_n8n n8n postgres-n8n-quizzpilot quizpilot_api_new quizpilot_client_new quizpilot_db_new quizpilot_n8n_new || true
            docker rm -f quizpilot_api quizpilot_client quizpilot_db quizpilot_n8n n8n postgres-n8n-quizzpilot quizpilot_api_new quizpilot_client_new quizpilot_db_new quizpilot_n8n_new || true

            export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}

            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d

            # Re-activation des migrations automatiques (maintenant que la donnée est là)
            sleep 20
            docker exec quizpilot_api python manage.py migrate
