name: Build and Deploy to VPS

on:
  push:
    branches:
      - "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API
        uses: docker/build-push-action@v6
        with:
          context: ./back-django
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/quizpilot_api:latest

      - name: Build and push Client
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/quizpilot_client:latest
          build-args: |
           VITE_API_URL=${{ secrets.VITE_API_URL }}
           VITE_N8N_WEBHOOK_URL=${{ secrets.VITE_N8N_WEBHOOK_URL }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create directory on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: mkdir -p /home/debian/quizpilot-docker

      - name: Copy docker-compose.prod.yml to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "docker-compose.prod.yml"
          target: "/home/debian/quizpilot-docker"

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/debian/quizpilot-docker

            echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" > .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env

            echo "DB_PASSWORD=\"${{ secrets.DB_PASSWORD }}\"" >> .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "ALLOWED_HOSTS=\"${{ secrets.ALLOWED_HOSTS }}\"" >> .env

            echo "SECRET_KEY=\"${{ secrets.SECRET_KEY }}\"" >> .env
            echo "DEBUG=${{ secrets.DEBUG }}" >> .env
            echo "CORS_ALLOWED_ORIGINS=\"${{ secrets.CORS_ALLOWED_ORIGINS }}\"" >> .env
            echo "CSRF_TRUSTED_ORIGINS=\"${{ secrets.CORS_ALLOWED_ORIGINS }}\"" >> .env

            docker stop $(docker ps -q --filter "name=^quizpilot")
            docker rm -f $(docker ps -aq --filter "name=^quizpilot")

            export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}

            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d

            sleep 20

            docker exec quizpilot_api python manage.py migrate



